name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/gventuri/pandas-ai/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  id: system-info
  attributes:
    label: System Info
    description: | 
      Please share your system info with us.
      OS version:
      Python version:
      The current version of `pandasai` being used:

    placeholder: pandasai version, platform, python version, ...
  validations:
    required: true

- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:

      ```python
      # All necessary imports at the beginning
      import pandas as pd
      from pandasai import SmartDataframe
      
      # Sample DataFrame
      df = pd.DataFrame({
          "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
          "gdp": [19294482071552, 2891615567872, 2411255037952, 3435817336832, 1745433788416, 1181205135360, 1607402389504, 1490967855104, 4380756541440, 14631844184064],
          "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12]
      })
      
      # Instantiate a LLM
      from pandasai.llm import OpenAI
      llm = OpenAI(api_token="YOUR_API_TOKEN")
      
      df = SmartDataframe(df, config={"llm": llm})
      df.chat('Which are the 5 happiest countries?')
      ```

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ````
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
