from typing import Any
from pandasai.pipelines.base_logic_unit import BaseLogicUnit
from pandasai.pipelines.logic_units.code_executor import BaseCodeExecutor


class SDFCodeExecutor(BaseLogicUnit):
    """
    Executes the code generated by the prompt
    """

    def execute(self, input: Any, **kwargs) -> Any:
        code_exec = BaseCodeExecutor()
        namespace = code_exec.execute(input, **kwargs)

        if "df" not in namespace:
            raise Exception("Unable to execute code: {input}")

        data = namespace["df"]

        return data
